# Every file an imported target names, across its configurations.
function(_tp_imported_locations target locations)
  get_target_property(_tp_configs ${target} IMPORTED_CONFIGURATIONS)
  set(_tp_properties IMPORTED_LOCATION)
  foreach(_tp_config IN LISTS _tp_configs)
    list(APPEND _tp_properties "IMPORTED_LOCATION_${_tp_config}")
  endforeach()
  set(_tp_found "")
  foreach(_tp_property IN LISTS _tp_properties)
    get_target_property(_tp_location ${target} ${_tp_property})
    if(_tp_location)
      list(APPEND _tp_found "${_tp_location}")
    endif()
  endforeach()
  set(${locations} "${_tp_found}" PARENT_SCOPE)
endfunction()

# Validate before choosing a default: unrelated system packages must not turn
# an ordinary developer or source-install configure into a hard failure.
function(_tp_check_streaming_grpc reason)
  find_package(gRPC CONFIG QUIET)
  if(NOT gRPC_FOUND)
    set(${reason} "TP_ENABLE_STREAMING_GRPC=ON requires the streaming-grpc vcpkg manifest feature." PARENT_SCOPE)
    return()
  endif()
  if(NOT VCPKG_TARGET_TRIPLET OR NOT VCPKG_INSTALLED_DIR)
    set(${reason} "Streaming gRPC requires the pinned vcpkg manifest toolchain." PARENT_SCOPE)
    return()
  endif()

  find_package(Protobuf CONFIG QUIET)
  if(NOT Protobuf_FOUND)
    set(${reason} "Streaming gRPC requires the pinned vcpkg protobuf package." PARENT_SCOPE)
    return()
  endif()

  # Triplet preference alone is insufficient: ports may ignore it. Check the
  # actual imported archives, including OpenSSL, before accepting the link model.
  set(_tp_streaming_prefix "${VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}")
  foreach(_tp_target IN ITEMS gRPC::grpc++ gRPC::grpc gRPC::gpr
                              protobuf::libprotobuf OpenSSL::SSL OpenSSL::Crypto)
    if(NOT TARGET ${_tp_target})
      set(${reason} "Streaming gRPC requires imported target ${_tp_target}." PARENT_SCOPE)
      return()
    endif()
    get_target_property(_tp_type ${_tp_target} TYPE)
    if(NOT _tp_type MATCHES "^(STATIC|UNKNOWN)_LIBRARY$")
      set(${reason} "Streaming gRPC requires static libraries: ${_tp_target} is ${_tp_type}." PARENT_SCOPE)
      return()
    endif()
    _tp_imported_locations(${_tp_target} _tp_locations)
    if(NOT _tp_locations)
      set(${reason} "Streaming gRPC target has no imported static archive: ${_tp_target}." PARENT_SCOPE)
      return()
    endif()
    foreach(_tp_location IN LISTS _tp_locations)
      cmake_path(IS_PREFIX _tp_streaming_prefix "${_tp_location}" NORMALIZE _tp_in_prefix)
      if(NOT _tp_in_prefix OR NOT _tp_location MATCHES "\\.(a|lib)$")
        set(${reason} "Streaming gRPC requires vcpkg static archives: ${_tp_target}." PARENT_SCOPE)
        return()
      endif()
    endforeach()
  endforeach()

  # The bindings are generated at build time, so the generators must be the
  # pinned ones too. They are host tools: any triplet of the install tree.
  foreach(_tp_target IN ITEMS protobuf::protoc gRPC::grpc_cpp_plugin)
    if(NOT TARGET ${_tp_target})
      set(${reason} "Streaming gRPC requires imported target ${_tp_target}." PARENT_SCOPE)
      return()
    endif()
    _tp_imported_locations(${_tp_target} _tp_locations)
    if(NOT _tp_locations)
      set(${reason} "Streaming gRPC code generator has no imported location: ${_tp_target}." PARENT_SCOPE)
      return()
    endif()
    foreach(_tp_location IN LISTS _tp_locations)
      cmake_path(IS_PREFIX VCPKG_INSTALLED_DIR "${_tp_location}" NORMALIZE _tp_in_prefix)
      if(NOT _tp_in_prefix)
        set(${reason} "Streaming gRPC requires vcpkg code generators: ${_tp_target}." PARENT_SCOPE)
        return()
      endif()
    endforeach()
  endforeach()
  set(${reason} "" PARENT_SCOPE)
endfunction()

set(_tp_streaming_default OFF)
# An explicit OFF must work even with an unusable system gRPC installation.
if(NOT DEFINED TP_ENABLE_STREAMING_GRPC OR TP_ENABLE_STREAMING_GRPC)
  _tp_check_streaming_grpc(_tp_streaming_unavailable)
  if(_tp_streaming_unavailable)
    if(TP_ENABLE_STREAMING_GRPC)
      message(FATAL_ERROR "${_tp_streaming_unavailable}")
    endif()
    message(STATUS "Streaming gRPC: default OFF (${_tp_streaming_unavailable})")
  else()
    set(_tp_streaming_default ON)
    message(STATUS "Streaming gRPC: static archives and code generators verified for ${VCPKG_TARGET_TRIPLET}")
  endif()
endif()
option(TP_ENABLE_STREAMING_GRPC
       "Build with the pinned static gRPC/protobuf streaming dependencies" ${_tp_streaming_default})
